import { describe, expect, it } from 'vitest'
import { applyMove, initialBoard, notationToSquare, opposite, type Side } from '../game/othello.ts'
import { buildJosekiDb } from './buildDb.ts'
import { hashBoard } from './normalize.ts'
import { collectMoveEvalRequests, parseNodeKey } from './openingBookPositions.ts'
import type { JosekiBookMove, JosekiNode, RawJosekiLine } from './types.ts'
import {
  buildMoveValuesByNode,
  buildOpeningBookDb,
  filterOpeningBook,
  isAutoGeneratedLineName,
  pruneUnreachableNodes,
  resolveMoveValue,
} from './buildOpeningBook.ts'

function makeNode(bookMoves: JosekiBookMove[], names: string[] = ['ライン']): JosekiNode {
  return { bookMoves, nonBookEval: null, names, isLeaf: false }
}

describe('isAutoGeneratedLineName', () => {
  it('WTHOR-####形式は自動命名と判定する', () => {
    expect(isAutoGeneratedLineName('WTHOR-0001')).toBe(true)
    expect(isAutoGeneratedLineName('WTHOR-9999')).toBe(true)
  })

  it('手作業の定石名は自動命名と判定しない', () => {
    expect(isAutoGeneratedLineName('虎')).toBe(false)
    expect(isAutoGeneratedLineName('Tora')).toBe(false)
  })
})

describe('resolveMoveValue', () => {
  it('terminal=trueならterminalValueをそのまま返す', () => {
    const value = resolveMoveValue(
      { nodeKey: 'n', move: 1, terminal: true, terminalValue: 12 },
      new Map(),
    )
    expect(value).toBe(12)
  })

  it('terminal=false・needsFlip=falseならpositionResultsの値をそのまま返す', () => {
    const value = resolveMoveValue(
      { nodeKey: 'n', move: 1, terminal: false, positionKey: 'p1', needsFlip: false },
      new Map([['p1', 5]]),
    )
    expect(value).toBe(5)
  })

  it('terminal=false・needsFlip=trueならpositionResultsの値を符号反転して返す', () => {
    const value = resolveMoveValue(
      { nodeKey: 'n', move: 1, terminal: false, positionKey: 'p1', needsFlip: true },
      new Map([['p1', 5]]),
    )
    expect(value).toBe(-5)
  })

  it('positionResultsに値が無ければ例外を投げる', () => {
    expect(() =>
      resolveMoveValue(
        { nodeKey: 'n', move: 1, terminal: false, positionKey: 'missing', needsFlip: true },
        new Map(),
      ),
    ).toThrow()
  })
})

describe('filterOpeningBook', () => {
  it('lossThreshold以上のbookMoveを除外し、生存したbookMoveにevalを格納する', () => {
    const nodes = new Map([
      [
        'node1',
        makeNode([
          { move: 1, weight: 0, eval: null },
          { move: 2, weight: 0, eval: null },
          { move: 3, weight: 0, eval: null },
        ]),
      ],
    ])
    const moveValuesByNode = new Map([
      [
        'node1',
        new Map([
          [1, 10], // best
          [2, 8], // loss=2 -> excluded (閾値2は「以上」で除外)
          [3, 9], // loss=1 -> survives
        ]),
      ],
    ])

    const { nodes: filtered, excluded } = filterOpeningBook(nodes, moveValuesByNode, 2)

    const node1 = filtered.get('node1')!
    expect(node1.bookMoves.map((bm) => bm.move).sort()).toEqual([1, 3])
    expect(node1.bookMoves.find((bm) => bm.move === 1)!.eval).toBe(10)
    expect(node1.bookMoves.find((bm) => bm.move === 3)!.eval).toBe(9)

    expect(excluded).toHaveLength(1)
    expect(excluded[0]).toMatchObject({ nodeKey: 'node1', move: 2, loss: 2, bestValue: 10, moveValue: 8 })
  })

  it('namedOriginは、ノードのnamesに自動命名(WTHOR-####)以外が1つでも含まれればtrue', () => {
    const nodes = new Map([
      [
        'namedNode',
        makeNode([{ move: 1, weight: 0, eval: null }], ['虎', 'WTHOR-0001']),
      ],
      [
        'autoNode',
        makeNode([{ move: 1, weight: 0, eval: null }], ['WTHOR-0002']),
      ],
    ])
    const moveValuesByNode = new Map([
      ['namedNode', new Map([[1, 0], [99, 10]])],
      ['autoNode', new Map([[1, 0], [99, 10]])],
    ])

    const { excluded } = filterOpeningBook(nodes, moveValuesByNode, 5)
    const named = excluded.find((e) => e.nodeKey === 'namedNode')!
    const auto = excluded.find((e) => e.nodeKey === 'autoNode')!
    expect(named.namedOrigin).toBe(true)
    expect(auto.namedOrigin).toBe(false)
  })

  it('moveValuesByNodeにノードのエントリが無ければそのノードは変更せずそのまま残す', () => {
    const node = makeNode([{ move: 1, weight: 0.5, eval: null }])
    const nodes = new Map([['orphan', node]])
    const { nodes: filtered, excluded } = filterOpeningBook(nodes, new Map(), 2)
    expect(filtered.get('orphan')).toBe(node)
    expect(excluded).toHaveLength(0)
  })

  it('bookMoveのmoveがmoveValuesByNodeに無ければ例外を投げる(全合法手を尽くしている前提の防御)', () => {
    const nodes = new Map([['node1', makeNode([{ move: 1, weight: 0, eval: null }])]])
    const moveValuesByNode = new Map([['node1', new Map([[2, 5]])]])
    expect(() => filterOpeningBook(nodes, moveValuesByNode, 2)).toThrow()
  })
})

describe('buildMoveValuesByNode', () => {
  it('複数requestsを nodeKey -> (move -> value) に集約する', () => {
    const requests = [
      { nodeKey: 'n1', move: 1, terminal: true, terminalValue: 4 },
      { nodeKey: 'n1', move: 2, terminal: false, positionKey: 'p1', needsFlip: true },
      { nodeKey: 'n2', move: 1, terminal: false, positionKey: 'p1', needsFlip: false },
    ]
    const positionResults = new Map([['p1', 3]])
    const byNode = buildMoveValuesByNode(requests, positionResults)
    expect(byNode.get('n1')!.get(1)).toBe(4)
    expect(byNode.get('n1')!.get(2)).toBe(-3)
    expect(byNode.get('n2')!.get(1)).toBe(3)
  })
})

describe('pruneUnreachableNodes', () => {
  // f5-f4-c3(ライン'A')とf5-d6-c4(ライン'B')の2ラインからDAGを構築し、
  // 「f5直後の局面」のbookMovesからd6を人為的に取り除いた(=悪手として
  // 除外されたことをシミュレートした)状態で、d6側のサブツリー
  // (d6直後の局面・c4直後の局面)だけが刈られることを確認する。
  const rawLines: RawJosekiLine[] = [
    { name: 'A', moves: ['f5', 'f4', 'c3'], firstMoveBasis: 'f5', depth: 3 },
    { name: 'B', moves: ['f5', 'd6', 'c4'], firstMoveBasis: 'f5', depth: 3 },
  ]
  const db = buildJosekiDb(rawLines)

  function keyAfter(notations: readonly string[]): string {
    let board = initialBoard()
    let side: Side = 'black'
    for (const n of notations) {
      board = applyMove(board, side, notationToSquare(n))
      side = opposite(side)
    }
    return hashBoard(board, side)
  }

  const rootKey = keyAfter([])
  const afterF5Key = keyAfter(['f5'])
  const afterF5F4Key = keyAfter(['f5', 'f4'])
  const afterF5F4C3Key = keyAfter(['f5', 'f4', 'c3'])
  const afterF5D6Key = keyAfter(['f5', 'd6'])
  const afterF5D6C4Key = keyAfter(['f5', 'd6', 'c4'])

  it('前提: フィルタ前のDAGは両ラインのノードをすべて持つ', () => {
    for (const key of [rootKey, afterF5Key, afterF5F4Key, afterF5F4C3Key, afterF5D6Key, afterF5D6C4Key]) {
      expect(db.nodes.has(key), `missing node for key derived from ${key}`).toBe(true)
    }
  })

  it('d6を除外(bookMovesから削除)すると、d6側のサブツリーだけが到達不能として刈られる', () => {
    const simulateFiltered = new Map(db.nodes)
    const afterF5Node = simulateFiltered.get(afterF5Key)!
    const d6Move = notationToSquare('d6')
    simulateFiltered.set(afterF5Key, {
      ...afterF5Node,
      bookMoves: afterF5Node.bookMoves.filter((bm) => bm.move !== d6Move),
    })

    const pruned = pruneUnreachableNodes(simulateFiltered)

    expect(pruned.has(rootKey)).toBe(true)
    expect(pruned.has(afterF5Key)).toBe(true)
    expect(pruned.has(afterF5F4Key)).toBe(true)
    expect(pruned.has(afterF5F4C3Key)).toBe(true)
    expect(pruned.has(afterF5D6Key)).toBe(false)
    expect(pruned.has(afterF5D6C4Key)).toBe(false)
  })

  it('何も除外しなければ全ノードが到達可能なまま残る', () => {
    const pruned = pruneUnreachableNodes(db.nodes)
    expect(pruned.size).toBe(db.nodes.size)
  })
})

describe('buildOpeningBookDb (統合、簡易な合成評価値で end-to-end 検証)', () => {
  const rawLines: RawJosekiLine[] = [
    { name: 'A', moves: ['f5', 'f4', 'c3'], firstMoveBasis: 'f5', depth: 3 },
    { name: 'B', moves: ['f5', 'd6', 'c4'], firstMoveBasis: 'f5', depth: 3 },
  ]
  const db = buildJosekiDb(rawLines)
  const { requests, positions } = collectMoveEvalRequests(db)

  // テスト用の合成評価値: OBF文字列中のXの数-Oの数(実際のEdax評価ではないが、
  // 決定的でrequests/positionsの配線を検証するには十分)。
  function syntheticScore(obf: string): number {
    let score = 0
    for (const c of obf) {
      if (c === 'X') score += 1
      else if (c === 'O') score -= 1
    }
    return score
  }
  const positionResults = new Map(positions.map((p) => [p.key, syntheticScore(p.board)]))

  it('excludedの全件がloss>=lossThresholdを満たす', () => {
    const { excluded } = buildOpeningBookDb(db, requests, positionResults, 2)
    for (const e of excluded) {
      expect(e.loss).toBeGreaterThanOrEqual(2)
      expect(e.loss).toBe(e.bestValue - e.moveValue)
    }
  })

  it('生存したbookMovesのevalはresolveMoveValueの結果と一致する', () => {
    const { db: result } = buildOpeningBookDb(db, requests, positionResults, 2)
    const moveValuesByNode = buildMoveValuesByNode(requests, positionResults)
    for (const [nodeKey, node] of result.nodes) {
      const moveValues = moveValuesByNode.get(nodeKey)
      if (!moveValues) continue
      for (const bookMove of node.bookMoves) {
        expect(bookMove.eval).toBe(moveValues.get(bookMove.move))
      }
    }
  })

  it('各ノードのbookMovesの重みは合計1になる(生存者がいる場合)', () => {
    const { db: result } = buildOpeningBookDb(db, requests, positionResults, 2)
    for (const node of result.nodes.values()) {
      if (node.bookMoves.length === 0) continue
      const total = node.bookMoves.reduce((sum, bm) => sum + bm.weight, 0)
      expect(total).toBeCloseTo(1, 10)
    }
  })

  it('刈り込み後の全ノードはルート(初期局面)から生存bookMovesを辿って到達可能', () => {
    const { db: result } = buildOpeningBookDb(db, requests, positionResults, 2)
    const rootKey = hashBoard(initialBoard(), 'black')
    expect(result.nodes.has(rootKey)).toBe(true)

    const reachable = new Set<string>([rootKey])
    const queue = [rootKey]
    while (queue.length > 0) {
      const key = queue.shift()!
      const node = result.nodes.get(key)!
      const { board, side } = parseNodeKey(key)
      for (const bm of node.bookMoves) {
        const childKey = hashBoard(applyMove(board, side, bm.move), opposite(side))
        if (result.nodes.has(childKey) && !reachable.has(childKey)) {
          reachable.add(childKey)
          queue.push(childKey)
        }
      }
    }

    expect(reachable.size).toBe(result.nodes.size)
    expect(result.nodes.size).toBeGreaterThan(0)
    expect(result.nodes.size).toBeLessThanOrEqual(db.nodes.size)
  })

  it('db.linesはそのまま素通しされる(フィルタ・刈り込みの対象外)', () => {
    const { db: result } = buildOpeningBookDb(db, requests, positionResults, 2)
    expect(result.lines).toBe(db.lines)
  })
})
