import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { applyMove, initialBoard, notationToSquare, opposite, type Side } from '../game/othello.ts'
import { buildJosekiDb } from './buildDb.ts'
import { hashBoard } from './normalize.ts'
import { collectMoveEvalRequests, parseNodeKey } from './openingBookPositions.ts'
import type { JosekiBookMove, JosekiNode, RawJosekiFile, RawJosekiLine } from './types.ts'
import {
  buildMoveValuesByNode,
  buildOpeningBookDb,
  checkNamedLineSurvival,
  collectNamedLineMoveKeys,
  filterOpeningBook,
  isAutoGeneratedLineName,
  protectedMoveKey,
  pruneUnreachableNodes,
  resolveMoveValue,
} from './buildOpeningBook.ts'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const RAW_JOSEKI_PATH = path.resolve(__dirname, '../../../bookgen/joseki-research.json')
const RAW_WTHOR_PATH = path.resolve(__dirname, '../../../bookgen/wthor-lines.json')

function loadRawLines(fixturePath: string): readonly RawJosekiLine[] {
  const raw = JSON.parse(readFileSync(fixturePath, 'utf-8')) as RawJosekiFile
  return raw.lines
}

function makeNode(bookMoves: JosekiBookMove[], names: string[] = ['ライン'], isLeaf = false): JosekiNode {
  return { bookMoves, nonBookEval: null, names, isLeaf }
}

describe('isAutoGeneratedLineName', () => {
  it('WTHOR-####形式は自動命名と判定する', () => {
    expect(isAutoGeneratedLineName('WTHOR-0001')).toBe(true)
    expect(isAutoGeneratedLineName('WTHOR-9999')).toBe(true)
  })

  it('手作業の定石名は自動命名と判定しない', () => {
    expect(isAutoGeneratedLineName('虎')).toBe(false)
    expect(isAutoGeneratedLineName('Tora')).toBe(false)
  })
})

describe('resolveMoveValue', () => {
  it('terminal=trueならterminalValueをそのまま返す', () => {
    const value = resolveMoveValue(
      { nodeKey: 'n', move: 1, terminal: true, terminalValue: 12 },
      new Map(),
    )
    expect(value).toBe(12)
  })

  it('terminal=false・needsFlip=falseならpositionResultsの値をそのまま返す', () => {
    const value = resolveMoveValue(
      { nodeKey: 'n', move: 1, terminal: false, positionKey: 'p1', needsFlip: false },
      new Map([['p1', 5]]),
    )
    expect(value).toBe(5)
  })

  it('terminal=false・needsFlip=trueならpositionResultsの値を符号反転して返す', () => {
    const value = resolveMoveValue(
      { nodeKey: 'n', move: 1, terminal: false, positionKey: 'p1', needsFlip: true },
      new Map([['p1', 5]]),
    )
    expect(value).toBe(-5)
  })

  it('positionResultsに値が無ければ例外を投げる', () => {
    expect(() =>
      resolveMoveValue(
        { nodeKey: 'n', move: 1, terminal: false, positionKey: 'missing', needsFlip: true },
        new Map(),
      ),
    ).toThrow()
  })
})

describe('filterOpeningBook (v2: 命名済みラインの手はlossに関わらず除外しない)', () => {
  it('保護対象でなければ、lossThreshold以上のbookMoveを除外し、生存したbookMoveにevalを格納する', () => {
    const nodes = new Map([
      [
        'node1',
        makeNode([
          { move: 1, weight: 0, eval: null },
          { move: 2, weight: 0, eval: null },
          { move: 3, weight: 0, eval: null },
        ]),
      ],
    ])
    const moveValuesByNode = new Map([
      [
        'node1',
        new Map([
          [1, 10], // best
          [2, 8], // loss=2, 保護対象外 -> 除外
          [3, 9], // loss=1 -> 生存(閾値未満)
        ]),
      ],
    ])

    const { nodes: filtered, flagged } = filterOpeningBook(nodes, moveValuesByNode, 2, new Set())

    const node1 = filtered.get('node1')!
    expect(node1.bookMoves.map((bm) => bm.move).sort()).toEqual([1, 3])
    expect(node1.bookMoves.find((bm) => bm.move === 1)!.eval).toBe(10)
    expect(node1.bookMoves.find((bm) => bm.move === 3)!.eval).toBe(9)

    expect(flagged).toHaveLength(1)
    expect(flagged[0]).toMatchObject({
      nodeKey: 'node1',
      move: 2,
      loss: 2,
      bestValue: 10,
      moveValue: 8,
      protectedByNamedLine: false,
      excludedFromBook: true,
    })
  })

  it('v2の中核: 保護対象(命名済みラインの手順)ならlossThreshold以上でも除外しない', () => {
    const nodes = new Map([
      [
        'node1',
        makeNode([
          { move: 1, weight: 0, eval: null },
          { move: 2, weight: 0, eval: null }, // 命名済みラインの手として保護される想定
        ]),
      ],
    ])
    const moveValuesByNode = new Map([
      [
        'node1',
        new Map([
          [1, 10], // best
          [2, -10], // loss=20、非常に悪い手だが保護対象
        ]),
      ],
    ])
    const protectedMoveKeys = new Set([protectedMoveKey('node1', 2)])

    const { nodes: filtered, flagged } = filterOpeningBook(nodes, moveValuesByNode, 2, protectedMoveKeys)

    const node1 = filtered.get('node1')!
    // 除外されず、両方のbookMoveが生存する(evalは通常どおり格納)。
    expect(node1.bookMoves.map((bm) => bm.move).sort()).toEqual([1, 2])
    expect(node1.bookMoves.find((bm) => bm.move === 2)!.eval).toBe(-10)

    // 「高lossだった」という事実自体はflaggedに残る(警告レポート用)。
    expect(flagged).toHaveLength(1)
    expect(flagged[0]).toMatchObject({
      nodeKey: 'node1',
      move: 2,
      loss: 20,
      protectedByNamedLine: true,
      excludedFromBook: false,
    })
  })

  it('全bookMovesが除外されたノードはisLeafがtrueに補正される(元がfalseでも)', () => {
    const nodes = new Map([
      [
        'node1',
        makeNode(
          [
            { move: 1, weight: 0, eval: null },
            { move: 2, weight: 0, eval: null },
          ],
          ['ライン'],
          false, // 元はisLeaf: false(まだ続きがある局面のつもりだった)
        ),
      ],
    ])
    // 両方とも保護対象外・高loss -> どちらも除外され、bookMovesが空になる
    // (bestValueは、bookMove化されていない別の合法手99から来ている想定)。
    const moveValuesByNode = new Map([
      [
        'node1',
        new Map([
          [1, 3], // loss=7
          [2, 2], // loss=8
          [99, 10], // best(非bookMove)
        ]),
      ],
    ])

    const { nodes: filtered } = filterOpeningBook(nodes, moveValuesByNode, 2, new Set())
    const node1 = filtered.get('node1')!
    expect(node1.bookMoves).toEqual([])
    expect(node1.isLeaf).toBe(true)
  })

  it('bookMovesが1件以上生存すればisLeafは元の値のまま変わらない', () => {
    const nodes = new Map([['node1', makeNode([{ move: 1, weight: 0, eval: null }], ['ライン'], false)]])
    const moveValuesByNode = new Map([['node1', new Map([[1, 10]])]])
    const { nodes: filtered } = filterOpeningBook(nodes, moveValuesByNode, 2, new Set())
    expect(filtered.get('node1')!.isLeaf).toBe(false)
  })

  it('namedOriginは、ノードのnamesに自動命名(WTHOR-####)以外が1つでも含まれればtrue(保護判定とは独立)', () => {
    const nodes = new Map([
      ['namedNode', makeNode([{ move: 1, weight: 0, eval: null }], ['虎', 'WTHOR-0001'])],
      ['autoNode', makeNode([{ move: 1, weight: 0, eval: null }], ['WTHOR-0002'])],
    ])
    const moveValuesByNode = new Map([
      ['namedNode', new Map([[1, 0], [99, 10]])],
      ['autoNode', new Map([[1, 0], [99, 10]])],
    ])

    // どちらも保護集合には含めない(namedOriginは「ノードの合流」のゆるい目印であり、
    // 「この手自体が保護対象か」とは別の軸であることを確認する)。
    const { flagged } = filterOpeningBook(nodes, moveValuesByNode, 5, new Set())
    const named = flagged.find((e) => e.nodeKey === 'namedNode')!
    const auto = flagged.find((e) => e.nodeKey === 'autoNode')!
    expect(named.namedOrigin).toBe(true)
    expect(named.protectedByNamedLine).toBe(false)
    expect(named.excludedFromBook).toBe(true)
    expect(auto.namedOrigin).toBe(false)
  })

  it('moveValuesByNodeにノードのエントリが無ければそのノードは変更せずそのまま残す', () => {
    const node = makeNode([{ move: 1, weight: 0.5, eval: null }])
    const nodes = new Map([['orphan', node]])
    const { nodes: filtered, flagged } = filterOpeningBook(nodes, new Map(), 2, new Set())
    expect(filtered.get('orphan')).toBe(node)
    expect(flagged).toHaveLength(0)
  })

  it('bookMoveのmoveがmoveValuesByNodeに無ければ例外を投げる(全合法手を尽くしている前提の防御)', () => {
    const nodes = new Map([['node1', makeNode([{ move: 1, weight: 0, eval: null }])]])
    const moveValuesByNode = new Map([['node1', new Map([[2, 5]])]])
    expect(() => filterOpeningBook(nodes, moveValuesByNode, 2, new Set())).toThrow()
  })
})

describe('buildMoveValuesByNode', () => {
  it('複数requestsを nodeKey -> (move -> value) に集約する', () => {
    const requests = [
      { nodeKey: 'n1', move: 1, terminal: true, terminalValue: 4 },
      { nodeKey: 'n1', move: 2, terminal: false, positionKey: 'p1', needsFlip: true },
      { nodeKey: 'n2', move: 1, terminal: false, positionKey: 'p1', needsFlip: false },
    ]
    const positionResults = new Map([['p1', 3]])
    const byNode = buildMoveValuesByNode(requests, positionResults)
    expect(byNode.get('n1')!.get(1)).toBe(4)
    expect(byNode.get('n1')!.get(2)).toBe(-3)
    expect(byNode.get('n2')!.get(1)).toBe(3)
  })
})

describe('collectNamedLineMoveKeys / checkNamedLineSurvival', () => {
  const rawLines: RawJosekiLine[] = [
    { name: 'A', moves: ['f5', 'f4', 'c3'], firstMoveBasis: 'f5', depth: 3 },
  ]

  it('collectNamedLineMoveKeysはラインの全手順(各局面,着手)をキー化する', () => {
    const keys = collectNamedLineMoveKeys(rawLines)
    expect(keys.size).toBe(3) // f5, f4, c3の3手

    let board = initialBoard()
    let side: Side = 'black'
    for (const notation of ['f5', 'f4', 'c3']) {
      const move = notationToSquare(notation)
      const key = hashBoard(board, side)
      expect(keys.has(protectedMoveKey(key, move)), `missing key for ${notation}`).toBe(true)
      board = applyMove(board, side, move)
      side = opposite(side)
    }
  })

  it('checkNamedLineSurvival: 全手順がbookDbに残っていればfullySurvived=true', () => {
    const db = buildJosekiDb(rawLines)
    const result = checkNamedLineSurvival(rawLines, db)
    expect(result).toEqual([{ name: 'A', totalMoves: 3, survivedMoves: 3, fullySurvived: true }])
  })

  it('checkNamedLineSurvival: 途中の手が無くなっていればfullySurvived=false', () => {
    const db = buildJosekiDb(rawLines)
    const f4Move = notationToSquare('f4')
    const afterF5Key = hashBoard(applyMove(initialBoard(), 'black', notationToSquare('f5')), 'white')
    const afterF5Node = db.nodes.get(afterF5Key)!
    const tampered = new Map(db.nodes)
    tampered.set(afterF5Key, { ...afterF5Node, bookMoves: afterF5Node.bookMoves.filter((bm) => bm.move !== f4Move) })

    const result = checkNamedLineSurvival(rawLines, { nodes: tampered, lines: db.lines })
    expect(result[0].fullySurvived).toBe(false)
    // f5・c3の2手は(各ステップが独立にチェックされるため)生存扱いのまま、
    // 途中のf4だけが生存カウントから外れる(f5-f4-c3の3手中2手)。
    expect(result[0].survivedMoves).toBe(2)
  })
})

describe('pruneUnreachableNodes', () => {
  // f5-f4-c3(ライン'A')とf5-d6-c4(ライン'B')の2ラインからDAGを構築し、
  // 「f5直後の局面」のbookMovesからd6を人為的に取り除いた(=悪手として
  // 除外されたことをシミュレートした)状態で、d6側のサブツリー
  // (d6直後の局面・c4直後の局面)だけが刈られることを確認する。
  const rawLines: RawJosekiLine[] = [
    { name: 'A', moves: ['f5', 'f4', 'c3'], firstMoveBasis: 'f5', depth: 3 },
    { name: 'B', moves: ['f5', 'd6', 'c4'], firstMoveBasis: 'f5', depth: 3 },
  ]
  const db = buildJosekiDb(rawLines)

  function keyAfter(notations: readonly string[]): string {
    let board = initialBoard()
    let side: Side = 'black'
    for (const n of notations) {
      board = applyMove(board, side, notationToSquare(n))
      side = opposite(side)
    }
    return hashBoard(board, side)
  }

  const rootKey = keyAfter([])
  const afterF5Key = keyAfter(['f5'])
  const afterF5F4Key = keyAfter(['f5', 'f4'])
  const afterF5F4C3Key = keyAfter(['f5', 'f4', 'c3'])
  const afterF5D6Key = keyAfter(['f5', 'd6'])
  const afterF5D6C4Key = keyAfter(['f5', 'd6', 'c4'])

  it('前提: フィルタ前のDAGは両ラインのノードをすべて持つ', () => {
    for (const key of [rootKey, afterF5Key, afterF5F4Key, afterF5F4C3Key, afterF5D6Key, afterF5D6C4Key]) {
      expect(db.nodes.has(key), `missing node for key derived from ${key}`).toBe(true)
    }
  })

  it('d6を除外(bookMovesから削除)すると、d6側のサブツリーだけが到達不能として刈られる', () => {
    const simulateFiltered = new Map(db.nodes)
    const afterF5Node = simulateFiltered.get(afterF5Key)!
    const d6Move = notationToSquare('d6')
    simulateFiltered.set(afterF5Key, {
      ...afterF5Node,
      bookMoves: afterF5Node.bookMoves.filter((bm) => bm.move !== d6Move),
    })

    const pruned = pruneUnreachableNodes(simulateFiltered)

    expect(pruned.has(rootKey)).toBe(true)
    expect(pruned.has(afterF5Key)).toBe(true)
    expect(pruned.has(afterF5F4Key)).toBe(true)
    expect(pruned.has(afterF5F4C3Key)).toBe(true)
    expect(pruned.has(afterF5D6Key)).toBe(false)
    expect(pruned.has(afterF5D6C4Key)).toBe(false)
  })

  it('何も除外しなければ全ノードが到達可能なまま残る', () => {
    const pruned = pruneUnreachableNodes(db.nodes)
    expect(pruned.size).toBe(db.nodes.size)
  })
})

describe('buildOpeningBookDb (統合、簡易な合成評価値で end-to-end 検証)', () => {
  const rawLines: RawJosekiLine[] = [
    { name: 'A', moves: ['f5', 'f4', 'c3'], firstMoveBasis: 'f5', depth: 3 },
    { name: 'B', moves: ['f5', 'd6', 'c4'], firstMoveBasis: 'f5', depth: 3 },
  ]
  const db = buildJosekiDb(rawLines)
  const { requests, positions } = collectMoveEvalRequests(db)
  // v2: このミニデータセットではAもBも「命名済みライン」扱い(WTHOR-####ではない)
  // なので、保護集合には両方の全手順を含める。フィルタの構造(重み正規化・
  // 到達可能性)を検証する目的では十分。
  const protectedMoveKeys = collectNamedLineMoveKeys(rawLines)

  // テスト用の合成評価値: OBF文字列中のXの数-Oの数(実際のEdax評価ではないが、
  // 決定的でrequests/positionsの配線を検証するには十分)。
  function syntheticScore(obf: string): number {
    let score = 0
    for (const c of obf) {
      if (c === 'X') score += 1
      else if (c === 'O') score -= 1
    }
    return score
  }
  const positionResults = new Map(positions.map((p) => [p.key, syntheticScore(p.board)]))

  it('flaggedの全件がloss>=lossThresholdを満たす', () => {
    const { flagged } = buildOpeningBookDb(db, requests, positionResults, 2, protectedMoveKeys)
    for (const f of flagged) {
      expect(f.loss).toBeGreaterThanOrEqual(2)
      expect(f.loss).toBe(f.bestValue - f.moveValue)
    }
  })

  it('AもBも命名済みラインとして保護されているため、このデータセットでは何も除外されない', () => {
    const { flagged } = buildOpeningBookDb(db, requests, positionResults, 2, protectedMoveKeys)
    expect(flagged.every((f) => f.protectedByNamedLine)).toBe(true)
    expect(flagged.every((f) => f.excludedFromBook === false)).toBe(true)
  })

  it('生存したbookMovesのevalはresolveMoveValueの結果と一致する', () => {
    const { db: result } = buildOpeningBookDb(db, requests, positionResults, 2, protectedMoveKeys)
    const moveValuesByNode = buildMoveValuesByNode(requests, positionResults)
    for (const [nodeKey, node] of result.nodes) {
      const moveValues = moveValuesByNode.get(nodeKey)
      if (!moveValues) continue
      for (const bookMove of node.bookMoves) {
        expect(bookMove.eval).toBe(moveValues.get(bookMove.move))
      }
    }
  })

  it('各ノードのbookMovesの重みは合計1になる(生存者がいる場合)', () => {
    const { db: result } = buildOpeningBookDb(db, requests, positionResults, 2, protectedMoveKeys)
    for (const node of result.nodes.values()) {
      if (node.bookMoves.length === 0) continue
      const total = node.bookMoves.reduce((sum, bm) => sum + bm.weight, 0)
      expect(total).toBeCloseTo(1, 10)
    }
  })

  it('刈り込み後の全ノードはルート(初期局面)から生存bookMovesを辿って到達可能', () => {
    const { db: result } = buildOpeningBookDb(db, requests, positionResults, 2, protectedMoveKeys)
    const rootKey = hashBoard(initialBoard(), 'black')
    expect(result.nodes.has(rootKey)).toBe(true)

    const reachable = new Set<string>([rootKey])
    const queue = [rootKey]
    while (queue.length > 0) {
      const key = queue.shift()!
      const node = result.nodes.get(key)!
      const { board, side } = parseNodeKey(key)
      for (const bm of node.bookMoves) {
        const childKey = hashBoard(applyMove(board, side, bm.move), opposite(side))
        if (result.nodes.has(childKey) && !reachable.has(childKey)) {
          reachable.add(childKey)
          queue.push(childKey)
        }
      }
    }

    expect(reachable.size).toBe(result.nodes.size)
    expect(result.nodes.size).toBeGreaterThan(0)
    expect(result.nodes.size).toBeLessThanOrEqual(db.nodes.size)
  })

  it('db.linesはそのまま素通しされる(フィルタ・刈り込みの対象外)', () => {
    const { db: result } = buildOpeningBookDb(db, requests, positionResults, 2, protectedMoveKeys)
    expect(result.lines).toBe(db.lines)
  })
})

describe('buildOpeningBookDb: 命名済み112ラインの完全生存(v2ポリシー、実データ+乱数風の敵対的評価値)', () => {
  // 実際のbookgen/joseki-research.json(112ライン)+wthor-lines.json(251ライン)を
  // 統合し、決定的だが「ランダムっぽい」合成評価値(局面キーのハッシュから導出)を
  // 与えることで、命名済みラインの手の一部も高loss(>=2)になるケースを意図的に
  // 発生させ、それでも除外されない(=保護ロジックが実データ規模で機能する)ことを
  // 確認する(2026-07-20オーケストレーター指摘: 命名済み112/112ラインの全生存確認)。
  const research = loadRawLines(RAW_JOSEKI_PATH)
  const wthor = loadRawLines(RAW_WTHOR_PATH)
  const rawLines = [...research, ...wthor]
  const db = buildJosekiDb(rawLines)
  const { requests, positions } = collectMoveEvalRequests(db)
  const protectedMoveKeys = collectNamedLineMoveKeys(research)

  function adversarialScore(key: string): number {
    let hash = 0
    for (let i = 0; i < key.length; i++) {
      hash = (hash * 31 + key.charCodeAt(i)) % 1000003
    }
    return (hash % 61) - 30 // -30..30の決定的な疑似乱数値
  }
  const positionResults = new Map(positions.map((p) => [p.key, adversarialScore(p.key)]))

  const { db: result, flagged } = buildOpeningBookDb(db, requests, positionResults, 2, protectedMoveKeys)

  it('保護対象(命名済みラインの手)は、lossが高くても実際には除外されない', () => {
    const protectedFlags = flagged.filter((f) => f.protectedByNamedLine)
    expect(protectedFlags.length).toBeGreaterThan(0) // この敵対的評価値では実際に高lossの保護対象手が発生する
    for (const f of protectedFlags) {
      expect(f.excludedFromBook).toBe(false)
    }
  })

  it('保護対象外(自動抽出ラインのみに乗る手)は高lossなら実際に除外される', () => {
    const excludedFlags = flagged.filter((f) => f.excludedFromBook)
    expect(excludedFlags.length).toBeGreaterThan(0)
    for (const f of excludedFlags) {
      expect(f.protectedByNamedLine).toBe(false)
    }
  })

  it('命名済み112ライン全ての手順が最終ブックに全て生存する(0/112の途中切断)', () => {
    const survival = checkNamedLineSurvival(research, result)
    expect(survival).toHaveLength(112)
    const notSurvived = survival.filter((r) => !r.fullySurvived)
    expect(notSurvived).toEqual([])
  })
})
