/**
 * T151(拡張ブック生成 フェーズ2/2、ステージ3): Edax評価結果を使って統合定石DAG
 * (`bookgen/joseki-research.json`+`bookgen/wthor-lines.json`)から
 * 「明白な悪手」を除外した対局専用の拡張ブック(`app/public/opening-book.json`)
 * を組み立てる純粋関数群。
 *
 * 手順(オーケストレーター確定の設計判断、`tasks/T151-book-eval-publish.md`参照):
 * 1. 各bookMoveに、その局面の**全合法手**中の最善値との差(`loss`)を計算する
 *    (`resolveMoveValue`/`computeLossesForNode`)。
 * 2. `loss >= lossThreshold`(既定2石)のbookMoveを除外する(`filterOpeningBook`)。
 * 3. 除外後に生存したbookMovesへ、`buildDb.ts`の`assignWeights`と同じロジックで
 *    重みを再割り当てする(頻度データが全件揃っていれば頻度比例、そうでなければ均等)。
 * 4. ルート局面(初期局面)から生存bookMovesだけを辿って到達可能なノードだけを
 *    残す(到達不能になったサブツリーを刈る、`pruneUnreachableNodes`)。
 */

import { applyMove, initialBoard, opposite, type Board, type Side } from '../game/othello.ts'
import { assignWeights } from './buildDb.ts'
import { hashBoard } from './normalize.ts'
import { parseNodeKey, type MoveEvalRequest } from './openingBookPositions.ts'
import type { JosekiBookMove, JosekiDb, JosekiNode } from './types.ts'

/** 自動命名ライン(WTHOR頻出ライン抽出、`bookgen/wthor-lines.json`、T150)の命名規則。 */
const AUTO_NAME_RE = /^WTHOR-\d+$/

/** ラインの名前が自動命名(WTHOR-####)かどうかを返す。 */
export function isAutoGeneratedLineName(name: string): boolean {
  return AUTO_NAME_RE.test(name)
}

/** Edaxが返した着手後局面の評価値(`positionKey` -> discDiff、着手後局面の手番視点)。 */
export type PositionEvalResults = ReadonlyMap<string, number>

/**
 * `MoveEvalRequest`1件を、ノードの手番視点の値(discDiff)に解決する。
 * `terminal: true` なら`terminalValue`をそのまま使い、そうでなければ
 * `positionResults`から着手後局面の値を引いて`needsFlip`に応じて符号反転する。
 */
export function resolveMoveValue(
  request: MoveEvalRequest,
  positionResults: PositionEvalResults,
): number {
  if (request.terminal) {
    if (request.terminalValue === undefined) {
      throw new Error(`resolveMoveValue: terminal request for node ${request.nodeKey} has no terminalValue`)
    }
    return request.terminalValue
  }
  if (request.positionKey === undefined) {
    throw new Error(`resolveMoveValue: non-terminal request for node ${request.nodeKey} has no positionKey`)
  }
  const raw = positionResults.get(request.positionKey)
  if (raw === undefined) {
    throw new Error(
      `resolveMoveValue: missing Edax eval result for position "${request.positionKey}" ` +
        `(node ${request.nodeKey}, move ${request.move})`,
    )
  }
  return request.needsFlip ? -raw : raw
}

/**
 * `requests`(ノード×全合法手)を`positionResults`で解決し、
 * `nodeKey -> (move -> value)` のマップにまとめる。
 */
export function buildMoveValuesByNode(
  requests: readonly MoveEvalRequest[],
  positionResults: PositionEvalResults,
): Map<string, Map<number, number>> {
  const byNode = new Map<string, Map<number, number>>()
  for (const request of requests) {
    const value = resolveMoveValue(request, positionResults)
    let moveValues = byNode.get(request.nodeKey)
    if (!moveValues) {
      moveValues = new Map()
      byNode.set(request.nodeKey, moveValues)
    }
    moveValues.set(request.move, value)
  }
  return byNode
}

/** 除外されたbookMove1件についての警告レポート用エントリ。 */
export interface ExcludedBookMove {
  readonly nodeKey: string
  readonly move: number
  /** その局面の全合法手中の最善値との差(石差、0以上)。 */
  readonly loss: number
  readonly bestValue: number
  readonly moveValue: number
  /** この局面を経由する定石ライン名。 */
  readonly names: readonly string[]
  /** `names`のいずれかが自動命名(WTHOR-####)でない場合`true`
   *  (命名済み定石由来の除外であることを示す)。 */
  readonly namedOrigin: boolean
}

/** `filterOpeningBook` の返り値。 */
export interface FilterOpeningBookResult {
  readonly nodes: Map<string, JosekiNode>
  readonly excluded: ExcludedBookMove[]
}

/**
 * 各ノードのbookMovesについて、`loss >= lossThreshold`のものを除外し、
 * 生存したbookMovesに`eval`(その手を打った場合の、手番視点の値)を格納する。
 * 重みの再計算はここでは行わない(呼び出し側で`assignWeights`を呼ぶ)。
 *
 * `moveValuesByNode`にエントリが無いノード(合法手0件、通常は起こらない)は
 * 元のノードをそのまま残す(防御的措置)。bookMoveの`move`が
 * `moveValuesByNode`に無い場合は、収集(`collectMoveEvalRequests`)が
 * 全合法手を尽くしているという前提が崩れていることを意味するため例外を投げる。
 */
export function filterOpeningBook(
  nodes: ReadonlyMap<string, JosekiNode>,
  moveValuesByNode: ReadonlyMap<string, ReadonlyMap<number, number>>,
  lossThreshold: number,
): FilterOpeningBookResult {
  const excluded: ExcludedBookMove[] = []
  const filteredNodes = new Map<string, JosekiNode>()

  for (const [nodeKey, node] of nodes) {
    const moveValues = moveValuesByNode.get(nodeKey)
    if (!moveValues || moveValues.size === 0) {
      filteredNodes.set(nodeKey, node)
      continue
    }

    const bestValue = Math.max(...moveValues.values())
    const namedOrigin = node.names.some((name) => !isAutoGeneratedLineName(name))
    const survivors: JosekiBookMove[] = []

    for (const bookMove of node.bookMoves) {
      const value = moveValues.get(bookMove.move)
      if (value === undefined) {
        throw new Error(
          `filterOpeningBook: no eval value for bookMove ${bookMove.move} at node ${nodeKey} ` +
            '(collectMoveEvalRequests should have covered every legal move)',
        )
      }
      const loss = bestValue - value
      if (loss >= lossThreshold) {
        excluded.push({ nodeKey, move: bookMove.move, loss, bestValue, moveValue: value, names: node.names, namedOrigin })
        continue
      }
      survivors.push({ ...bookMove, eval: value, weight: 0 })
    }

    filteredNodes.set(nodeKey, { ...node, bookMoves: survivors })
  }

  return { nodes: filteredNodes, excluded }
}

/**
 * `nodeKey`(局面)と正規化座標系の着手マスから、着手後局面のノードキーを返す。
 * `buildJosekiDb`がDAGを構築する際と同じ「着手のたびに単純に手番を反転する」
 * 規約(実際にパスが発生する場合の特殊扱いはしない)に合わせてある。到達可能性の
 * 判定(`pruneUnreachableNodes`)は、この規約で実際に構築された`db.nodes`の
 * キー空間と整合していなければならないため、意図的に同じ規約を使う。
 */
function childNodeKey(nodeKey: string, move: number): string {
  const { board, side }: { board: Board; side: Side } = parseNodeKey(nodeKey)
  const after = applyMove(board, side, move)
  return hashBoard(after, opposite(side))
}

/**
 * ルート局面(標準初期局面、黒番)から生存bookMovesだけを辿って到達可能な
 * ノードだけを残す(要件3「到達不能サブツリーを刈る」)。
 */
export function pruneUnreachableNodes(nodes: ReadonlyMap<string, JosekiNode>): Map<string, JosekiNode> {
  const rootKey = hashBoard(initialBoard(), 'black')
  const reachable = new Set<string>()
  const queue: string[] = []

  if (nodes.has(rootKey)) {
    reachable.add(rootKey)
    queue.push(rootKey)
  }

  while (queue.length > 0) {
    const key = queue.shift()!
    const node = nodes.get(key)
    if (!node) continue
    for (const bookMove of node.bookMoves) {
      const childKey = childNodeKey(key, bookMove.move)
      if (!reachable.has(childKey) && nodes.has(childKey)) {
        reachable.add(childKey)
        queue.push(childKey)
      }
    }
  }

  const pruned = new Map<string, JosekiNode>()
  for (const [key, node] of nodes) {
    if (reachable.has(key)) pruned.set(key, node)
  }
  return pruned
}

/**
 * ステージ3全体(フィルタ+重み再計算+到達不能ノードの刈り込み)をまとめて行う。
 * `db.lines`(ライン名・moveSeq等のメタデータ)はフィルタ・刈り込みの対象では
 * ないため素通しする(joseki.jsonとのスキーマ互換性のため保持するだけで、
 * 対局モードのブック消費コードは`db.lines`を参照しない)。
 */
export function buildOpeningBookDb(
  db: JosekiDb,
  requests: readonly MoveEvalRequest[],
  positionResults: PositionEvalResults,
  lossThreshold: number,
): { db: JosekiDb; excluded: ExcludedBookMove[] } {
  const moveValuesByNode = buildMoveValuesByNode(requests, positionResults)
  const { nodes: filteredNodes, excluded } = filterOpeningBook(db.nodes, moveValuesByNode, lossThreshold)
  assignWeights(filteredNodes)
  const prunedNodes = pruneUnreachableNodes(filteredNodes)

  return { db: { nodes: prunedNodes, lines: db.lines }, excluded }
}
