/**
 * T151(拡張ブック生成 フェーズ2/2、ステージ3): Edax評価結果を使って統合定石DAG
 * (`bookgen/joseki-research.json`+`bookgen/wthor-lines.json`)から
 * 「明白な悪手」を除外した対局専用の拡張ブック(`app/public/opening-book.json`)
 * を組み立てる純粋関数群。
 *
 * 手順(オーケストレーター確定の設計判断、`tasks/T151-book-eval-publish.md`参照。
 * v2、2026-07-20: 初版の一律除外は検収データで命名済み112ライン中69本が途中切断
 * (32本がply<=5)・除外135件中76件が閾値境界のロス2ちょうど、と定石カバレッジを
 * 削りすぎることが判明したため改定):
 * 1. 各bookMoveに、その局面の**全合法手**中の最善値との差(`loss`)を計算する
 *    (`resolveMoveValue`)。
 * 2. `loss >= lossThreshold`(既定2石)のbookMoveのうち、**命名済みライン
 *    (`bookgen/joseki-research.json`由来)の実際の手順に含まれない手だけ**を
 *    除外する(`filterOpeningBook`)。命名済みラインの手順に含まれる手は
 *    loss値に関わらず除外しない(`collectNamedLineMoveKeys`で判定した
 *    `protectedMoveKeys`、evalは通常どおり格納し、警告レポートには
 *    「高loss・保護により残存」として引き続き記載する)。
 * 3. 除外後に生存したbookMovesへ、`buildDb.ts`の`assignWeights`と同じロジックで
 *    重みを再割り当てする(頻度データが全件揃っていれば頻度比例、そうでなければ均等)。
 * 4. ルート局面(初期局面)から生存bookMovesだけを辿って到達可能なノードだけを
 *    残す(到達不能になったサブツリーを刈る、`pruneUnreachableNodes`)。
 *    命名済みラインの手は一切除外されないため、112ライン全ての経路が
 *    ルートからの到達可能性を保ち、必ず生存する。
 * 5. あるノードの全bookMovesが除外された場合、そのノードの`isLeaf`を`true`に
 *    補正する(2026-07-20レビュー指摘: bookMoves=[]なのに`isLeaf: false`のままだと
 *    `app.tsx`の`evaluateHumanMove`の`!josekiHit.isLeaf`判定が「定石」ソースだと
 *    誤判定してしまう不整合があった)。
 */

import { applyMove, initialBoard, notationToSquare, opposite, type Board, type Side } from '../game/othello.ts'
import { assignWeights } from './buildDb.ts'
import { isAutoGeneratedLineName } from './lineNaming.ts'
import { hashBoard, opForFirstMove } from './normalize.ts'
import { parseNodeKey, type MoveEvalRequest } from './openingBookPositions.ts'
import { transformSquare } from './symmetry.ts'
import type { JosekiBookMove, JosekiDb, JosekiNode, RawJosekiLine } from './types.ts'

export { isAutoGeneratedLineName }

/** Edaxが返した着手後局面の評価値(`positionKey` -> discDiff、着手後局面の手番視点)。 */
export type PositionEvalResults = ReadonlyMap<string, number>

/**
 * `MoveEvalRequest`1件を、ノードの手番視点の値(discDiff)に解決する。
 * `terminal: true` なら`terminalValue`をそのまま使い、そうでなければ
 * `positionResults`から着手後局面の値を引いて`needsFlip`に応じて符号反転する。
 */
export function resolveMoveValue(
  request: MoveEvalRequest,
  positionResults: PositionEvalResults,
): number {
  if (request.terminal) {
    if (request.terminalValue === undefined) {
      throw new Error(`resolveMoveValue: terminal request for node ${request.nodeKey} has no terminalValue`)
    }
    return request.terminalValue
  }
  if (request.positionKey === undefined) {
    throw new Error(`resolveMoveValue: non-terminal request for node ${request.nodeKey} has no positionKey`)
  }
  const raw = positionResults.get(request.positionKey)
  if (raw === undefined) {
    throw new Error(
      `resolveMoveValue: missing Edax eval result for position "${request.positionKey}" ` +
        `(node ${request.nodeKey}, move ${request.move})`,
    )
  }
  return request.needsFlip ? -raw : raw
}

/**
 * `requests`(ノード×全合法手)を`positionResults`で解決し、
 * `nodeKey -> (move -> value)` のマップにまとめる。
 */
export function buildMoveValuesByNode(
  requests: readonly MoveEvalRequest[],
  positionResults: PositionEvalResults,
): Map<string, Map<number, number>> {
  const byNode = new Map<string, Map<number, number>>()
  for (const request of requests) {
    const value = resolveMoveValue(request, positionResults)
    let moveValues = byNode.get(request.nodeKey)
    if (!moveValues) {
      moveValues = new Map()
      byNode.set(request.nodeKey, moveValues)
    }
    moveValues.set(request.move, value)
  }
  return byNode
}

/** `nodeKey`と正規化座標系の`move`から、`protectedMoveKeys`用の複合キーを作る。 */
export function protectedMoveKey(nodeKey: string, move: number): string {
  return `${nodeKey}::${move}`
}

/** 1本の生ライン(`RawJosekiLine`)を初期局面から順に適用し、各手について
 *  「その手を打つ直前のノードキー」と「正規化座標系の着手マス」を返す。
 *  `buildDb.ts`の`buildJosekiDb`と同じ正規化・シミュレーション手順
 *  (初手をf5基準に変換してから初期局面に順に適用する)を独立に再現しており、
 *  同じ`RawJosekiLine`を渡せば`buildJosekiDb`が構築するノードキーと一致する。 */
function walkRawLine(raw: RawJosekiLine): { nodeKey: string; move: number }[] {
  const originalSquares = raw.moves.map(notationToSquare)
  if (originalSquares.length === 0) return []
  const op = opForFirstMove(originalSquares[0])
  const normalizedSquares = originalSquares.map((sq) => transformSquare(op, sq))

  const steps: { nodeKey: string; move: number }[] = []
  let board = initialBoard()
  let side: Side = 'black'
  for (const move of normalizedSquares) {
    steps.push({ nodeKey: hashBoard(board, side), move })
    board = applyMove(board, side, move)
    side = opposite(side)
  }
  return steps
}

/**
 * 命名済みライン(`namedLines`、通常は`bookgen/joseki-research.json`の`lines`)の
 * 実際の手順に含まれる(ノード, 着手)の組を全て集めた集合を返す
 * (`protectedMoveKey`形式の文字列)。`filterOpeningBook`はこの集合に含まれる
 * bookMoveを、lossの大小に関わらず除外しない(v2の中心的なポリシー)。
 */
export function collectNamedLineMoveKeys(namedLines: readonly RawJosekiLine[]): Set<string> {
  const keys = new Set<string>()
  for (const raw of namedLines) {
    for (const { nodeKey, move } of walkRawLine(raw)) {
      keys.add(protectedMoveKey(nodeKey, move))
    }
  }
  return keys
}

/** 命名済みライン1本についての生存確認結果。 */
export interface NamedLineSurvivalResult {
  readonly name: string
  readonly totalMoves: number
  readonly survivedMoves: number
  readonly fullySurvived: boolean
}

/**
 * `namedLines`の各ラインについて、その実際の手順(全ての(ノード, 着手)の組)が
 * `bookDb`(フィルタ・刈り込み後の最終的なopening-book)の中にbookMoveとして
 * 全て残っているかを確認する。v2の設計上、命名済みラインの手は除外されない
 * ため理論上は必ず`fullySurvived: true`になるはずだが、ビルドスクリプトの
 * レポート・回帰テストの両方で実データに対して直接検証する
 * (2026-07-20のオーケストレーター指摘: 命名済み112/112ラインの全生存確認)。
 */
export function checkNamedLineSurvival(
  namedLines: readonly RawJosekiLine[],
  bookDb: JosekiDb,
): NamedLineSurvivalResult[] {
  return namedLines.map((raw) => {
    const steps = walkRawLine(raw)
    const survivedMoves = steps.filter(({ nodeKey, move }) => {
      const node = bookDb.nodes.get(nodeKey)
      return node !== undefined && node.bookMoves.some((bm) => bm.move === move)
    }).length
    return {
      name: raw.name,
      totalMoves: steps.length,
      survivedMoves,
      fullySurvived: survivedMoves === steps.length,
    }
  })
}

/** loss>=lossThresholdだった1件(除外されたか、命名済みラインの手として保護され
 *  生存したかを問わない)についての警告レポート用エントリ。 */
export interface HighLossBookMove {
  readonly nodeKey: string
  readonly move: number
  /** その局面の全合法手中の最善値との差(石差、0以上)。 */
  readonly loss: number
  readonly bestValue: number
  readonly moveValue: number
  /** この局面を経由する定石ライン名。 */
  readonly names: readonly string[]
  /** `names`のいずれかが自動命名(WTHOR-####)でない場合`true`
   *  (このノードに命名済みラインが合流していることを示す、ゆるい目印)。
   *  実際に「この手自体」が命名済みラインの手順かどうかは`protectedByNamedLine`を見る。 */
  readonly namedOrigin: boolean
  /** この(ノード, 着手)が命名済みラインの実際の手順に含まれる場合`true`
   *  (v2: この場合、lossに関わらず除外されない)。 */
  readonly protectedByNamedLine: boolean
  /** 実際にbookMovesから除外されたかどうか(`loss >= lossThreshold && !protectedByNamedLine`)。 */
  readonly excludedFromBook: boolean
}

/** `filterOpeningBook` の返り値。 */
export interface FilterOpeningBookResult {
  readonly nodes: Map<string, JosekiNode>
  readonly flagged: HighLossBookMove[]
}

/**
 * 各ノードのbookMovesについて、`loss >= lossThreshold`かつ`protectedMoveKeys`に
 * 含まれない(=命名済みラインの実際の手順ではない)ものだけを除外し、
 * 生存したbookMovesに`eval`(その手を打った場合の、手番視点の値)を格納する。
 * 重みの再計算はここでは行わない(呼び出し側で`assignWeights`を呼ぶ)。
 *
 * `loss >= lossThreshold`の全件(除外されたか保護され生存したかを問わない)を
 * `flagged`として返す(警告レポート用、v2でも「高lossだった」という事実自体は
 * 引き続き記録する)。
 *
 * ノードの全bookMovesが除外された場合、そのノードの`isLeaf`を`true`に補正する
 * (2026-07-20レビュー指摘、ファイル先頭コメント手順5参照)。
 *
 * `moveValuesByNode`にエントリが無いノード(合法手0件、通常は起こらない)は
 * 元のノードをそのまま残す(防御的措置)。bookMoveの`move`が
 * `moveValuesByNode`に無い場合は、収集(`collectMoveEvalRequests`)が
 * 全合法手を尽くしているという前提が崩れていることを意味するため例外を投げる。
 */
export function filterOpeningBook(
  nodes: ReadonlyMap<string, JosekiNode>,
  moveValuesByNode: ReadonlyMap<string, ReadonlyMap<number, number>>,
  lossThreshold: number,
  protectedMoveKeys: ReadonlySet<string>,
): FilterOpeningBookResult {
  const flagged: HighLossBookMove[] = []
  const filteredNodes = new Map<string, JosekiNode>()

  for (const [nodeKey, node] of nodes) {
    const moveValues = moveValuesByNode.get(nodeKey)
    if (!moveValues || moveValues.size === 0) {
      filteredNodes.set(nodeKey, node)
      continue
    }

    const bestValue = Math.max(...moveValues.values())
    const namedOrigin = node.names.some((name) => !isAutoGeneratedLineName(name))
    const survivors: JosekiBookMove[] = []

    for (const bookMove of node.bookMoves) {
      const value = moveValues.get(bookMove.move)
      if (value === undefined) {
        throw new Error(
          `filterOpeningBook: no eval value for bookMove ${bookMove.move} at node ${nodeKey} ` +
            '(collectMoveEvalRequests should have covered every legal move)',
        )
      }
      const loss = bestValue - value
      const isHighLoss = loss >= lossThreshold
      const isProtected = protectedMoveKeys.has(protectedMoveKey(nodeKey, bookMove.move))
      const excludedFromBook = isHighLoss && !isProtected

      if (isHighLoss) {
        flagged.push({
          nodeKey,
          move: bookMove.move,
          loss,
          bestValue,
          moveValue: value,
          names: node.names,
          namedOrigin,
          protectedByNamedLine: isProtected,
          excludedFromBook,
        })
      }

      if (excludedFromBook) continue
      survivors.push({ ...bookMove, eval: value, weight: 0 })
    }

    filteredNodes.set(nodeKey, {
      ...node,
      bookMoves: survivors,
      isLeaf: survivors.length === 0 ? true : node.isLeaf,
    })
  }

  return { nodes: filteredNodes, flagged }
}

/**
 * `nodeKey`(局面)と正規化座標系の着手マスから、着手後局面のノードキーを返す。
 * `buildJosekiDb`がDAGを構築する際と同じ「着手のたびに単純に手番を反転する」
 * 規約(実際にパスが発生する場合の特殊扱いはしない)に合わせてある。到達可能性の
 * 判定(`pruneUnreachableNodes`)は、この規約で実際に構築された`db.nodes`の
 * キー空間と整合していなければならないため、意図的に同じ規約を使う。
 */
function childNodeKey(nodeKey: string, move: number): string {
  const { board, side }: { board: Board; side: Side } = parseNodeKey(nodeKey)
  const after = applyMove(board, side, move)
  return hashBoard(after, opposite(side))
}

/**
 * ルート局面(標準初期局面、黒番)から生存bookMovesだけを辿って到達可能な
 * ノードだけを残す(要件3「到達不能サブツリーを刈る」)。v2では命名済みラインの
 * 手が一切除外されないため、命名済み112ラインの経路は必ずこの到達可能集合に
 * 含まれる。
 */
export function pruneUnreachableNodes(nodes: ReadonlyMap<string, JosekiNode>): Map<string, JosekiNode> {
  const rootKey = hashBoard(initialBoard(), 'black')
  const reachable = new Set<string>()
  const queue: string[] = []

  if (nodes.has(rootKey)) {
    reachable.add(rootKey)
    queue.push(rootKey)
  }

  while (queue.length > 0) {
    const key = queue.shift()!
    const node = nodes.get(key)
    if (!node) continue
    for (const bookMove of node.bookMoves) {
      const childKey = childNodeKey(key, bookMove.move)
      if (!reachable.has(childKey) && nodes.has(childKey)) {
        reachable.add(childKey)
        queue.push(childKey)
      }
    }
  }

  const pruned = new Map<string, JosekiNode>()
  for (const [key, node] of nodes) {
    if (reachable.has(key)) pruned.set(key, node)
  }
  return pruned
}

/**
 * ステージ3全体(フィルタ+重み再計算+到達不能ノードの刈り込み)をまとめて行う。
 * `db.lines`(ライン名・moveSeq等のメタデータ)はフィルタ・刈り込みの対象では
 * ないため素通しする(joseki.jsonとのスキーマ互換性のため保持するだけで、
 * 対局モードのブック消費コードは`db.lines`を参照しない)。
 */
export function buildOpeningBookDb(
  db: JosekiDb,
  requests: readonly MoveEvalRequest[],
  positionResults: PositionEvalResults,
  lossThreshold: number,
  protectedMoveKeys: ReadonlySet<string>,
): { db: JosekiDb; flagged: HighLossBookMove[] } {
  const moveValuesByNode = buildMoveValuesByNode(requests, positionResults)
  const { nodes: filteredNodes, flagged } = filterOpeningBook(
    db.nodes,
    moveValuesByNode,
    lossThreshold,
    protectedMoveKeys,
  )
  assignWeights(filteredNodes)
  const prunedNodes = pruneUnreachableNodes(filteredNodes)

  return { db: { nodes: prunedNodes, lines: db.lines }, flagged }
}
