/**
 * 定石ラインの「自動命名かどうか」の判定(T151)。
 *
 * `bookgen/wthor-lines.json`(WTHOR頻出ライン抽出、T150)のラインは
 * `WTHOR-####` という機械的な連番で命名されており、`bookgen/joseki-research.json`
 * (T016系、手作業で収集した112ライン)のような意味のある定石名を持たない。
 * `traceDisplay.ts`(表示、内部IDを生でユーザーに見せない)と
 * `buildOpeningBook.ts`(悪手除外ポリシー、命名済みラインの手は除外しない)の
 * 両方がこの判定を必要とするため、重複定義を避けて1箇所にまとめる
 * (2026-07-20 レビュー指摘: AUTO_NAME_REの二重定義を解消)。
 */

const AUTO_NAME_RE = /^WTHOR-\d+$/

/** ラインの名前が自動命名(`WTHOR-####`)かどうかを返す。 */
export function isAutoGeneratedLineName(name: string): boolean {
  return AUTO_NAME_RE.test(name)
}
