import importlib.util
import json
import tempfile
import unittest
from pathlib import Path


MODULE_PATH = Path(__file__).with_name("endgame_bench.py")
SPEC = importlib.util.spec_from_file_location("endgame_bench", MODULE_PATH)
bench = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(bench)


class EndgameBenchTests(unittest.TestCase):
    def test_parse_edax_batch_uses_final_exact_row_and_internal_time(self):
        output = """
*** problem # 1 ***
 depth|score|       time   |  nodes (N)
 8@73%  +19        0:00.003         52452
   18   +28        0:00.016        677188
*** problem # 2 ***
 0@73%   -2        0:00.001            12
   20    -6        1:02.125          9000
"""
        positions = [{"id": "a"}, {"id": "b"}]
        rows = bench.parse_edax_output(output, positions)
        self.assertEqual(rows[0], {"id": "a", "score": 28, "elapsedSeconds": 0.016, "nodes": 677188})
        self.assertEqual(rows[1]["score"], -6)
        self.assertEqual(rows[1]["elapsedSeconds"], 62.125)

    def test_atomic_checkpoint_resume_skips_completed_jobs_and_is_stable(self):
        jobs = [{"key": str(index), "value": index} for index in range(5)]

        def run_to(path, stop_after=None):
            calls = []
            checkpoint = bench.Checkpoint(path, {"fixture": 1})

            def worker(job):
                calls.append(job["key"])
                return {"value": job["value"] * 2}

            bench.execute_jobs(checkpoint, "fixture", jobs, worker, stop_after)
            return checkpoint, calls

        with tempfile.TemporaryDirectory() as directory:
            resumed_path = Path(directory) / "resumed.json"
            first, first_calls = run_to(resumed_path, 2)
            self.assertEqual(first_calls, ["0", "1"])
            resumed, resumed_calls = run_to(resumed_path)
            self.assertEqual(resumed_calls, ["2", "3", "4"])

            full, full_calls = run_to(Path(directory) / "full.json")
            self.assertEqual(full_calls, ["0", "1", "2", "3", "4"])
            self.assertEqual(resumed.section("fixture"), full.section("fixture"))
            json.loads(resumed_path.read_text(encoding="utf-8"))

    def test_e50_exact_uses_combined_proof_budget(self):
        rows = []
        for position_id, empties, high_nodes, low_nodes in (
            ("a", 20, 70000, 80000),
            ("b", 20, 90000, 90000),
            ("c", 21, 70000, 80000),
            ("d", 21, 90000, 90000),
        ):
            for window, nodes in (("fail_high", high_nodes), ("fail_low", low_nodes)):
                rows.append({
                    "id": position_id, "empties": empties, "budget": 160000,
                    "windowKind": window, "run": {"completed": True, "nodes": nodes},
                })
        self.assertEqual(bench.e50(rows, 160000, True), 21)
        self.assertEqual(bench.e50(rows, 160000, False), 21)

    def test_aggregate_uses_only_complete_speed_repetitions(self):
        positions = bench.read_json(bench.POSITIONS)["positions"]
        expected = [position for position in positions if 20 <= position["empties"] <= 24]
        speed = {}
        for position in expected:
            for implementation in ("engine", "edax"):
                elapsed = {"elapsedUs": 2_000_000} if implementation == "engine" else {"elapsedSeconds": 1.0}
                speed[f"{implementation}:0:{position['id']}"] = {
                    "implementation": implementation,
                    "repetition": 0,
                    "id": position["id"],
                    "empties": position["empties"],
                    "run": elapsed,
                }
        speed[f"engine:1:{expected[0]['id']}"] = {
            "implementation": "engine",
            "repetition": 1,
            "id": expected[0]["id"],
            "empties": expected[0]["empties"],
            "run": {"elapsedUs": 100_000_000},
        }
        checkpoint = type("Fixture", (), {"value": {"sections": {"speed": speed}}})()
        summary = bench.aggregate(checkpoint)["speed20To24"]
        self.assertEqual(summary["completeRepetitionsUsed"], [0])
        self.assertEqual(summary["partialRepetitionsExcluded"], [1])
        self.assertEqual(summary["completedPositions"], len(expected))
        self.assertAlmostEqual(summary["geometricMeanRatio"], 2.0)

    def test_committed_manifest_has_60_side_to_move_scores(self):
        if not bench.POSITIONS.exists():
            self.skipTest("manifest is generated by the T098 measurement step")
        document = bench.read_json(bench.POSITIONS)
        self.assertEqual(len(document["positions"]), 60)
        for position in document["positions"]:
            self.assertIsInstance(position["exactScore"], int)
            self.assertEqual(position["scorePerspective"], "side_to_move")


if __name__ == "__main__":
    unittest.main()
